### ISSUE TITLE
Pretrained model loading

### ISSUE THREAD

**Issue by BinSpa** [ChenDelong1999/RemoteCLIP#10]
When I tried to load the pre-trained model provided by the author using the ITRA method, I found that it can only be loaded through the '--resume' parameter for existing checkpoints. Moreover, the author's model could not be loaded successfully due to inconsistencies in some layers. I believe that in the 'openclip' loading method within model.py, code to load the model should be added.

**Comment by ChenDelong1999** [comment]
Hi, thanks for your interest in running RemoteCLIP on the [`ITRA`](https://itra.readthedocs.io/) codebase. Our model was trained with [`ITRA`](https://itra.readthedocs.io/), but in order to make our pretrained model accessed more conveniently, we have converted the checkpoints into the [`OpenCLIP`](https://github.com/mlfoundations/open_clip) compatible format.

It is possible to load RemoteCLIP through `ITRA` by modifying the code in [`model.py`](https://github.com/ChenDelong1999/ITRA/blob/main/itra/model/model.py) a bit.  Please specify `args.text_model_builder=='openclip'` and `args.image_model_builder=='openclip'` and add codes to load RemoteCLIP checkpoints below [this line](https://github.com/ChenDelong1999/ITRA/blob/main/itra/model/model.py#L33) and [this line](https://github.com/ChenDelong1999/ITRA/blob/main/itra/model/model.py#L126).
