### ISSUE TITLE
Fine tuning?

### ISSUE THREAD

**Issue by BradNeuberg** [ChenDelong1999/RemoteCLIP#20]
Great paper and work! Thank you for publishing this.

In your github repo I don't see training or fine tuning code or details. Are those available?

Thanks!

**Comment by ChenDelong1999** [comment]
Yes we didn't include training/finetuning codes in this repo.

However, as the RemoteCLIP checkpoint is provided in OpenCLIP format, it's possible to finetune RemoteCLIP with the OpenCLIP codebase.

Please see [here](https://github.com/mlfoundations/open_clip?tab=readme-ov-file#training-clip) for more details.

Thank you : )

**Comment by Pengyu-gis** [comment]
Thank you for your excellent work, I would like to ask a follow up question, are you using tif format files or jpg format files for training? (Since this may affect fine tuning).
As a lot of remote sensing image data are tif files, if I want to fine-tune based on tif, is it unable to do so with openclip's format?

Hoping you can help clear up my confusion, thanks for your time!
